=== amida-tech/blue-button/lib/validator/schemas/plan_of_care.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema",
    "properties": {
         "plan": {
            "type": "object",
            "properties": {
                "$ref": "http://local.com/common_models#/properties/cda_coded_entry"
            }
        },
        "type": {
            "type": "string"
        },
        "date_time": {
            "$ref": "http://local.com/common_models#/properties/cda_date"
        },
        "identifiers": {
            "type": "array",
            "items": {
                "$ref": "http://local.com/common_models#/properties/cda_id"
            },
            "minItems": 1
        }
    },
    "required": [
        "plan"
    ],
    "additionalProperties": false
}

=== amida-tech/blue-button/test/fixtures/file-snippets/generatedJSON/CCD_1_Plan_Of_Care.json
[
    {
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89a4-1121bc809b4a"
            }
        ],
        "date_time": {
            "center": {
                "date": "2012-05-12T00:00:00Z",
                "precision": "day"
            }
        },
        "type": "observation"
    },
    {
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89a4-1121bc809a5c"
            }
        ],
        "date_time": {
            "center": {
                "date": "2012-05-12T00:00:00Z",
                "precision": "day"
            }
        },
        "type": "act"
    },
    {
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89a4-1121bc809b4d"
            }
        ],
        "date_time": {
            "center": {
                "date": "2012-05-12T00:00:00Z",
                "precision": "day"
            }
        },
        "type": "encounter"
    },
    {
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89c4-1121bc809b5a"
            }
        ],
        "date_time": {
            "center": {
                "date": "2012-05-12T00:00:00Z",
                "precision": "day"
            }
        },
        "type": "procedure"
    }
]

=== amida-tech/blue-button/test/fixtures/file-snippets/json/CCD_1_Plan_Of_Care.json
[
    {
        "date_time": {
            "center": {
                    "date": "2012-05-12T00:00:00Z",
                    "precision": "day"
                }
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89a4-1121bc809b4a"
            }
        ],
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "type": "observation"
    },
    {
        "date_time": {
            "center": {
                    "date": "2012-05-12T00:00:00Z",
                    "precision": "day"
                }
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89a4-1121bc809a5c"
            }
        ],
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "type": "act"
    },
    {
        "date_time": {
            "center": {
                    "date": "2012-05-12T00:00:00Z",
                    "precision": "day"
                }
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89a4-1121bc809b4d"
            }
        ],
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "type": "encounter"
    },
    {
        "date_time": {
            "center": {
                    "date": "2012-05-12T00:00:00Z",
                    "precision": "day"
                }
        },
        "identifiers": [
            {
                "identifier": "9a6d1bac-17d3-4195-89c4-1121bc809b5a"
            }
        ],
        "plan": {
            "name": "Colonoscopy",
            "code": "73761001",
            "code_system_name": "SNOMED CT"
        },
        "type": "procedure"
    }
]
